services:

    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: training-app
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - train
    db:
        image: postgres:15
        container_name: training-db
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5440:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - train

    nginx:
        image: nginx:alpine
        container_name: training-nginx
        ports:
            - "82:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - train

volumes:
    pgdata:

networks:
    train:
